---
title: "new_covid_analysis"
author: "Gabe Cederberg"
date: "11/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(tigris_use_cache = TRUE)

# Loading the important packages.

library(readr)
library(janitor)
library(ggthemes)
library(haven)
library(infer)
library(readxl)
library(viridis)  
library(gganimate)
library(tidycensus)
library(RCurl)
library(tidyverse)
library(zoo)
```

```{r, echo = FALSE}
# state_text <- getURL("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv")
state <- read_csv("all-states-history.csv")

a <- state %>% 
  group_by(state) %>% 
  arrange(date) %>% 
  mutate(daily_hosp = hospitalized - lag(hospitalized, k = 1))
a

a %>% 
  group_by(date) %>% 
  summarize(viral = sum(totalTestsViralIncrease),
            all = sum(totalTestResultsIncrease)) %>% 
  mutate(pct_pcr = viral/all) %>% 
  filter(pct_pcr > 0 & pct_pcr <1) %>% 
  ggplot(aes(date, pct_pcr)) +
  geom_point() +
  geom_abline()

a %>% 
  filter(state == "MN") %>% 
  ggplot(aes(date, hospitalizedCurrently)) +
  geom_point()
```

```{r}
a %>% 
  filter(!is.na(totalTestsPeopleAntigen)) %>% 
 # group_by(state) %>% 
  count(state)

a %>% 
  filter(state == "IA") %>% 
    mutate(new_antigen = totalTestsPeopleAntigen - lag(totalTestsPeopleAntigen, k = 1)) %>% 
  ggplot(aes(date, new_antigen)) +
  geom_point()

```

```{r, warning = FALSE}
national <- read_csv("national-history.csv")

b <- national %>% 
  mutate(tests_7day = rollmean(totalTestResultsIncrease, k = 7, fill = NA))
         
         
         
b %>%          
  ggplot() +
  geom_point(aes(date, totalTestResultsIncrease)) +
    geom_line(aes(date, tests_7day, color = states, color.legend = F)) +
  theme_classic() +
  labs(
    title = "Number of COVID-19 Tests Performed Each Day Nationally",
   # subtitle = "Counties that lean Republican tend to have higher community transmission rates",
       y = "Number of Tests Performed",
       x = "Date",
    caption = "Data from: The COVID Tracking Project") +
    theme(legend.position = "none")
    

```

